### ISSUE TITLE
Drawscript

### ISSUE THREAD

**Issue by bcocanougher** [jwittenbach/muscle-viz#3]
@jwittenbach As I am still drawscriptless, when you get a chance could you export the new curves to code and send it to me? I'll take care of putting them into the json file.

**Comment by jwittenbach** [comment]
@bcoke Happy to! 

[shapes_raw.txt](https://github.com/jwittenbach/med-viz/files/55964/shapes_raw.txt)

**Comment by bcocanougher** [comment]
@jwittenbach Great! Thanks!
