### ISSUE TITLE
Default 5 button

### ISSUE THREAD

**Issue by bcocanougher** [jwittenbach/muscle-viz#4]
What would be really nice is either a new "full strength" button or a default that automatically colors all muscles at 5 (if on a 6 point scale from 0-5) -- or just defaults to coloring all at the max of the scale. Most patients will have full strength. That way you only have to click boxes that are different. That should cut down on the time needed to use the tool.

**Comment by jwittenbach** [comment]
Great idea. The current ability to set the colormap was just a temporary feature for playing around with colormaps, but ideally we wouldn't have that functionality visible by default. I'll try putting in a "full strength" button in place of that.
