### ISSUE TITLE
Fixing spacing in safari

### ISSUE THREAD

**Issue by bcocanougher** [jwittenbach/muscle-viz#5]
@jwittenbach The full strength button is perfect! I'm planning to send it out to some clinicians to try out next week. I think it is good enough now for pilot testers to see what they do and don't like about it. The only remaining issue is the weird spacing in Safari. It looks perfect in Chrome and Firefox, but is difficult to read in Safari. My attempt to fix it by adding spaces didn't seem to work. Do you know how to fix this? Those that use it on a mobile device or iPad will be using Safari, so I do think it is important to fix.

**Comment by bcocanougher** [comment]
@jwittenbach Also, is it possible to add the scale as: 

0
1 -
1
1+
2-
2
2+
3 -
3
3 +
4 - 
4
4 +
5

There are some that will complain that only 4 should have plus and minus, but others use it. If we get a complaint about extra plus and minus categories we can remove them.

I'm not sure if it is worth fixing in the current configuration if we are going to make a nice new button layout anyway. If it is more than 10 minutes of work, let's just wait for the buttons.

**Comment by jwittenbach** [comment]
@bcocanougher I think that should be pretty simple. If I switch it to that scale, do you want to come figure out a good colormap for it? I'll let you know when I push the changes, and then you can put in a good 14-point color scheme?

I haven't tried it on Safari yet, but I'll look into how we can fix that -- good point about iPad and iPhones.

As for nice buttons, I think that's the next big step. It's going to take a big refactoring, which I've started working on this afternoon in a separate branch. I'll try to make a lightweight framework for drawing shapes and images to the canvas as well as having callbacks for click events. Then the entire app can be on the canvas. I know there are frameworks out there already that can do this, but I think it would be fun to try to implement it myself -- it would probably take just as long as learning one of the big frameworks.

**Comment by bcocanougher** [comment]
@jwittenbach I guess I didn't think about a 14-point color scheme. Maybe that is too many...I will look to see what I can come up with.

Re: nice buttons. Your plan sounds excellent. I am all for you implementing your own version; you'll learn more and it'll look nicer in the end.

How much more work would it be to wrap this up into an application that could be downloaded on an iPhone or iPad? And if you make it for the apple store do you have to rewrite everything for android?

**Comment by jwittenbach** [comment]
@bcocanougher I hadn't thought about putting it in a downloadable app. I guess we should think carefully about what the best way to distribute the application will be.

From some preliminary searching, it _appears_ that it shouldn't be too hard to turn a web-app into a mobile. We could use something like one of the folowing:
- https://cordova.apache.org/
- http://phonegap.com/

This should help us avoid needing to learn the API for each mobile OS, which would be a huge undertaking.

**Comment by bcocanougher** [comment]
@jwittenbach Those look like excellent options.

First we should get things up and running in the browser, then we can try and migrate it over to an app. The feedback I've received so far was pro-tablet; I don't think we would be wasting our time with an app.

**Comment by bcocanougher** [comment]
@jwittenbach I'll start looking at using the tools for apps you linked above. The spacing in Safari looks great now!
