### ISSUE TITLE
Medical Legal Department

### ISSUE THREAD

**Issue by bcocanougher** [jwittenbach/muscle-viz#6]
@jwittenbach @mcocanougher  Welcome Matthew! You can update us on any HIPPA compliance issues here. Feel free to include links if you want us to see where you're looking; of course we probably won't understand what they mean, so you can also just give us a summary of what we should do moving forward.

**Comment by mcocanougher** [comment]
Here's the best article I've found so far:

http://www.thesecurityadvocate.com/2014/06/05/compliance-for-developers-of-medical-applications-and-software-under-hipaa-and-other-regulations/

I'm now looking more specifically at whether or not the app would make you a "business associate" under HIPAA which would require additional safety steps to make sure patient information was not disclosed.

**Comment by bcocanougher** [comment]
@mcocanougher This is a very nice article. Ideally we wouldn't be storing any information on the app itself; we would provide a save button that would allow the information to be stored locally on the user's device. I'm not sure if we are then responsible for how they use it. I would hope not.

**Comment by bcocanougher** [comment]
@mcocanougher @jwittenbach The HIPAA disclaimer is now [here](https://github.com/jwittenbach/med-viz/blob/master/HIPAA-Disclaimer.md). We can edit it from there.
