### ISSUE TITLE
disappearing muscles

### ISSUE THREAD

**Issue by bcocanougher** [jwittenbach/muscle-viz#8]
Here's a note from Pomi:

Hi Ben,
 
Quick note – when you select for certain muscles to go away through “config” only one side of the thumb abductors go away and for some reason for the hip flexors, something happens where if you take any other muscles out – then one of the hip flexors disappears… 

Thanks!
Pomi

**Comment by jwittenbach** [comment]
Looks like the "numbers" for the left/right thumb abductors must have gotten crossed with those for the left/right hip flexors -- @bcocanougher can you check the Illustrator file and make sure that they're in the right order in the Illustrator file?
